config/routes.rb
Freeject::Application.routes.draw do
  match "dashboard", :to => "pages#dashboard"
  devise_for :users
  resources :projects do
    resources :stories
  end
  root :to => "pages#index"
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :stories
  # Validations
  validates :name, :presence => true, :length => {:maximum => 50}
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :project
  
  validates :title, :story_type, :description, :project_id, :presence => true
  
  attr_accessible :title, :story_type, :description, :project_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Validations
  validates :username, :presence => true, :uniqueness => true
  
  # Include default devise modules. Others available are:
  # :encryptable, :confirmable, :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :token_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout :layout_by_resource

  def after_sign_in_path_for(resource)
    stored_location_for(:user) || root_path
  end

  protected

    def layout_by_resource
      if devise_controller?
        "devise"
      else
        "application"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  stream

  before_filter :authenticate_user!
  def index
  end

  def dashboard
    
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  expose(:projects) { Project.all }
  expose(:project)
  respond_to :html, :json

  def index
    respond_with projects
  end

  def show
    respond_with project
  end

  def new
    respond_with project
  end

  def edit
    respond_with project
  end

  def create
    if project.save
      flash[:notice] = "Project was successfully created."
      respond_with project
    else
      render :new
    end
  end

  def update
    if project.update_attributes(params[:project])
      flash[:notice] = "Project was successfully updated."
      respond_with project
    else
      render :edit
    end
  end

  def destroy
    project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  respond_to :html
  before_filter :find_project
  def new
    @story = @project.stories.build
  end
  
  def create
    @story = @project.stories.build(params[:story])
    if @story.save
      flash[:notice] = "Successfully added story to project."
      redirect_to project_path(@project)
    else
      render :action => 'new'
    end
  end
  
  protected
  
    def find_project
      @project = Project.find(params[:project_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_if?(name)
    "active" if controller_name == name
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/_header.html.erb
<nav class="obj_right text_right">
  <%= link_to "Logout", destroy_user_session_path %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freeject</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id='container'>
      <section class='obj_left first' id='left_side'>
        <h1>freeject</h1>
        <p class='left_margin_10'>
          <% if current_user %>
            <%= current_user.username %>
            |
            <%= link_to "Logout", destroy_user_session_path %>
          <% end %>
        </p>
        <nav>
          <ul>
            <li><%= link_to "Dashboard", root_path, :class => active_if?("pages") %></li>
            <li><%= link_to "Projects", projects_path, :class => active_if?("projects") %></li>
          </ul>
        </nav>
      </section>
      <section class='obj_left last' id='right_side'>
        <% if notice %>
          <p class="success fade"><%= notice %></p>
        <% elsif alert %>
          <p class='error fade'><%= alert %></p>
        <% end %>
        <%= yield %>
      </section>
      <div class="clear"></div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freeject</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id='container' class='no_border'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h1>Pages#dashboard</h1>
<%= link_to "Projects", projects_path %>

app/views/pages/index.html.erb
<h1>Pages#index</h1>

app/views/projects/_form.html.erb
<%= semantic_form_for project, :html => {:class => 'horizontal_form'} do |f| %>
  <%= f.semantic_errors %>
  <%= f.inputs %>
  <%= f.buttons do %>
    <%= f.commit_button :class => 'blue styled_button' %>
  <% end %>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% unless projects.nil? %>
  <% for p in projects do %>
    <tr>
      <td><%= p.name %></td>
      <td><%= p.description %></td>
      <td><%= link_to 'Show', p %></td>
      <td><%= link_to 'Edit', edit_project_path(p) %></td>
      <td><%= link_to 'Destroy', p, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= project.name %>
</p>

<p>
  <b>Description:</b>
  <%= project.description %>
</p>

<p>
  <%= link_to "Add Story", new_project_story_path(project) %>
</p>

<div id="backlog">
  <%= project.stories.each do |s| %>
    <%= s.title %>
  <% end %>
</div>


<%= link_to 'Edit', edit_project_path(project) %> |
<%= link_to 'Back', projects_path %>

app/views/stories/_form.html.erb
<%= semantic_form_for [@project, @story] do |f| %>
  <%= f.inputs do %>
    <%= f.input :title, :label => "Story Title" %>
    <%= f.input :story_type, :label => "Story Type", :as => "select", :collection => ["Feature", "Bug", "Release"] %>
    <%= f.input :description %>
  <% end %>
  <%= f.buttons :commit %>
<% end %>

app/views/stories/new.html.erb
<%= render 'form' %>